### PR TITLE
Handling restart

### PR DESCRIPTION
**Pull request by papey**
Linked to #17

### CODE REVIEW

**Comment by papey** [comment]
Needs master rebase but looks ok-ish

**Comment by papey** [comment]
Rebased and ready for review, @athoune

**Review by athoune — APPROVED** [review]

**Comment by athoune** [comment]
`functional_tests mlecarme$ make test` is broken.

**Review by athoune — CHANGES_REQUESTED** [review]
`functional_tests mlecarme$ make test` is peted

**Comment by papey** [comment]
Unpeted

**Pull request merged**
